version: '3.8'
services:
  api:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
