version: '3.8'
services:
  api:
    image: svyatstupak/api:latest
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
