version: '3.8'
services:
  api:
    build:
      context: .
      args:
        - MEDUSA_BACKEND_URL=http://64.225.110.85:9000
    ports:
      - "9000:9000"
      - "7001:7001"
      - "7002:7002"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
      - MEDUSA_BACKEND_URL=http://64.225.110.85:9000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
